//! Persistent project statistics written to `.yggdra/stats.json`.
//!
//! Stats survive across sessions and accumulate indefinitely, giving a
//! birds-eye view of how heavily the agent (and user) have been using
//! each tool and how many tokens have been consumed overall.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

const STATS_FILENAME: &str = "stats.json";

/// Per-tool call statistics.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ToolStats {
    /// Number of times the tool was invoked successfully.
    pub calls: u64,
    /// Number of invocations that returned an error.
    pub failures: u64,
    /// Total bytes of output produced by successful calls.
    pub output_bytes: u64,
}

/// Query result statistics for search-like tools.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct QueryStats {
    /// Individual result counts per query (e.g., [5, 12, 0, 3])
    pub result_counts: Vec<u64>,
    /// Average results per query
    pub avg_results: f64,
    /// Total queries executed
    pub total_queries: u64,
}

/// Cumulative project statistics persisted to `.yggdra/stats.json`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct Stats {
    // ── Tool usage ──────────────────────────────────────────────────────────
    /// Per-tool call and failure counts.
    pub tools: HashMap<String, ToolStats>,

    // ── Query result statistics ─────────────────────────────────────────────
    /// Per-tool query statistics (e.g., ripgrep, knowledge searches).
    pub query_results: HashMap<String, QueryStats>,

    // ── LLM usage ───────────────────────────────────────────────────────────
    /// Total number of LLM inference requests sent (streaming + non-streaming).
    pub llm_requests: u64,
    /// Cumulative prompt tokens sent to the model.
    pub prompt_tokens: u64,
    /// Cumulative tokens generated by the model.
    pub gen_tokens: u64,
    /// Exponential moving average of tokens-per-second (α = 0.2).
    /// Stored as a fixed-point integer (value × 100) to stay JSON-friendly.
    pub avg_tok_per_s_x100: u64,

    // ── Session metadata ─────────────────────────────────────────────────────
    /// Total number of yggdra sessions started in this project.
    pub sessions: u64,
    /// Unix timestamp (seconds) of the most recent session start.
    pub last_active_unix: u64,
    /// Cumulative wall-clock seconds spent in yggdra for this project.
    pub uptime_seconds: u64,

    // ── Context management ───────────────────────────────────────────────────
    /// Number of times the sliding-window context trim fired.
    pub context_trims: u64,
    /// Number of `/compress` compactions run.
    pub compressions: u64,
}

impl Stats {
    /// Load from `.yggdra/stats.json`, returning a zeroed default if missing or corrupt.
    pub fn load(project_dir: &Path) -> Self {
        let path = Self::path(project_dir);
        match std::fs::read_to_string(&path) {
            Ok(s) => serde_json::from_str(&s).unwrap_or_default(),
            Err(_) => Self::default(),
        }
    }

    /// Write to `.yggdra/stats.json` atomically via a temp file.
    pub fn save(&self, project_dir: &Path) {
        let path = Self::path(project_dir);
        if let Ok(json) = serde_json::to_string_pretty(self) {
            // Write to a temp file then rename for atomicity
            let tmp = path.with_extension("tmp");
            if std::fs::write(&tmp, &json).is_ok() {
                let _ = std::fs::rename(&tmp, &path);
            }
        }
    }

    fn path(project_dir: &Path) -> PathBuf {
        project_dir.join(".yggdra").join(STATS_FILENAME)
    }

    // ── Mutation helpers ─────────────────────────────────────────────────────

    /// Record a tool invocation.  `output_bytes` is `0` on failure.
    pub fn record_tool(&mut self, tool_name: &str, success: bool, output_bytes: usize) {
        let entry = self.tools.entry(tool_name.to_string()).or_default();
        if success {
            entry.calls += 1;
            entry.output_bytes += output_bytes as u64;
        } else {
            entry.failures += 1;
        }
    }

    /// Record query results for a search/query tool (e.g., ripgrep, knowledge search).
    /// `result_count` is the number of results returned by the query.
    pub fn record_query_result(&mut self, tool_name: &str, result_count: u64) {
        let entry = self.query_results.entry(tool_name.to_string()).or_default();
        entry.result_counts.push(result_count);
        entry.total_queries += 1;
        entry.avg_results = entry.result_counts.iter().sum::<u64>() as f64 / entry.total_queries as f64;
    }

    /// Record a completed LLM inference.
    pub fn record_llm(
        &mut self,
        prompt_tokens: u32,
        gen_tokens: u32,
        tok_per_s: Option<f64>,
    ) {
        self.llm_requests += 1;
        self.prompt_tokens += prompt_tokens as u64;
        self.gen_tokens += gen_tokens as u64;

        // Update EMA (α = 0.2)
        if let Some(rate) = tok_per_s {
            let new_x100 = (rate * 100.0).round() as u64;
            if self.avg_tok_per_s_x100 == 0 {
                self.avg_tok_per_s_x100 = new_x100;
            } else {
                // EMA: new = 0.2 * sample + 0.8 * old
                self.avg_tok_per_s_x100 =
                    (20 * new_x100 + 80 * self.avg_tok_per_s_x100) / 100;
            }
        }
    }

    /// Call once on each yggdra startup.
    pub fn on_session_start(&mut self) {
        self.sessions += 1;
        self.last_active_unix = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);
    }

    /// Add elapsed seconds to cumulative uptime.
    pub fn add_uptime(&mut self, seconds: u64) {
        self.uptime_seconds += seconds;
    }

    /// Convenience: average tok/s as a float.
    pub fn avg_tok_per_s(&self) -> f64 {
        self.avg_tok_per_s_x100 as f64 / 100.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    fn tmpdir(name: &str) -> PathBuf {
        let dir = env::temp_dir().join(format!("yggdra_stats_{}", name));
        let yggdra = dir.join(".yggdra");
        std::fs::create_dir_all(&yggdra).unwrap();
        dir
    }

    #[test]
    fn test_default_is_zeroed() {
        let s = Stats::default();
        assert_eq!(s.llm_requests, 0);
        assert_eq!(s.sessions, 0);
        assert!(s.tools.is_empty());
        assert!(s.query_results.is_empty());
    }

    #[test]
    fn test_record_tool_success() {
        let mut s = Stats::default();
        s.record_tool("rg", true, 1024);
        s.record_tool("rg", true, 512);
        s.record_tool("rg", false, 0);
        let t = &s.tools["rg"];
        assert_eq!(t.calls, 2);
        assert_eq!(t.failures, 1);
        assert_eq!(t.output_bytes, 1536);
    }

    #[test]
    fn test_record_query_result_single() {
        let mut s = Stats::default();
        s.record_query_result("rg", 5);
        let q = &s.query_results["rg"];
        assert_eq!(q.total_queries, 1);
        assert_eq!(q.result_counts.len(), 1);
        assert_eq!(q.result_counts[0], 5);
        assert!((q.avg_results - 5.0).abs() < 0.001);
    }

    #[test]
    fn test_record_query_result_multiple() {
        let mut s = Stats::default();
        s.record_query_result("rg", 10);
        s.record_query_result("rg", 5);
        s.record_query_result("rg", 15);
        let q = &s.query_results["rg"];
        assert_eq!(q.total_queries, 3);
        assert_eq!(q.result_counts.len(), 3);
        assert_eq!(q.result_counts, vec![10, 5, 15]);
        assert!((q.avg_results - 10.0).abs() < 0.001); // (10+5+15)/3 = 10
    }

    #[test]
    fn test_record_query_result_zero() {
        let mut s = Stats::default();
        s.record_query_result("rg", 0);
        s.record_query_result("rg", 3);
        let q = &s.query_results["rg"];
        assert_eq!(q.total_queries, 2);
        assert!((q.avg_results - 1.5).abs() < 0.001); // (0+3)/2 = 1.5
    }

    #[test]
    fn test_record_llm() {
        let mut s = Stats::default();
        s.record_llm(100, 50, Some(25.0));
        assert_eq!(s.llm_requests, 1);
        assert_eq!(s.prompt_tokens, 100);
        assert_eq!(s.gen_tokens, 50);
        assert_eq!(s.avg_tok_per_s_x100, 2500); // seeded at first sample
    }

    #[test]
    fn test_ema_update() {
        let mut s = Stats::default();
        s.record_llm(0, 0, Some(20.0)); // seed: 2000
        s.record_llm(0, 0, Some(40.0)); // 0.2*4000 + 0.8*2000 = 800+1600 = 2400
        assert_eq!(s.avg_tok_per_s_x100, 2400);
    }

    #[test]
    fn test_on_session_start() {
        let mut s = Stats::default();
        s.on_session_start();
        s.on_session_start();
        assert_eq!(s.sessions, 2);
        assert!(s.last_active_unix > 0);
    }

    #[test]
    fn test_save_and_load() {
        let dir = tmpdir("save_load");
        let mut s = Stats::default();
        s.on_session_start();
        s.record_tool("editfile", true, 200);
        s.record_llm(50, 30, Some(15.0));
        s.record_query_result("rg", 5);
        s.save(&dir);

        let loaded = Stats::load(&dir);
        assert_eq!(loaded.sessions, 1);
        assert_eq!(loaded.llm_requests, 1);
        assert_eq!(loaded.tools["editfile"].calls, 1);
        assert_eq!(loaded.query_results["rg"].total_queries, 1);
        assert_eq!(loaded.query_results["rg"].result_counts[0], 5);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_load_missing_returns_default() {
        let dir = env::temp_dir().join("yggdra_stats_missing_xyz123");
        let s = Stats::load(&dir);
        assert_eq!(s.sessions, 0);
    }

    #[test]
    fn test_avg_tok_per_s_float() {
        let mut s = Stats::default();
        s.avg_tok_per_s_x100 = 2500;
        assert!((s.avg_tok_per_s() - 25.0).abs() < 0.01);
    }
}
